// Copyright © 2026 Apple Inc.

import Foundation
import Testing

@testable import MLXVLM

/// Goldens computed by running the reference helpers from
/// `mlx_vlm/models/qwen4_exp/language.py` (pure integer code) directly:
/// any drift here means the PLE embedding gathers garbage rows.
@Suite("qwen4_exp n-gram hash parity")
struct Qwen4ExpNGramHashTests {
    @Test("splitmix64 matches the reference")
    func splitmix() {
        #expect(Qwen4ExpNGramHash.splitmix64(0) == 16_294_208_416_658_607_535)
        #expect(Qwen4ExpNGramHash.splitmix64(12345) == 2_454_886_589_211_414_944)
    }

    @Test("layer multipliers match, including the ple-layer seed offset")
    func multipliers() {
        #expect(
            Qwen4ExpNGramHash.layerMultipliers(
                unigramVocabSize: 152_064, ngramSize: 4, pleLayerIndex: 0, seed: 42)
                == [27_654_209_115_627, 49_074_646_729_357, 4_153_004_413_633, 4_742_919_160_989])
        #expect(
            Qwen4ExpNGramHash.layerMultipliers(
                unigramVocabSize: 152_064, ngramSize: 4, pleLayerIndex: 2, seed: 42)
                == [17_966_118_997_155, 21_276_791_440_793, 47_673_772_944_719, 38_069_068_554_069])
    }

    @Test("prime search matches")
    func primes() {
        #expect(Qwen4ExpNGramHash.nthPrimeAfter(99_999, count: 1) == 100_003)
        #expect(Qwen4ExpNGramHash.nthPrimeAfter(99_999, count: 5) == 100_057)
    }

    @Test("head vocab layout is consecutive primes with running offsets")
    func layout() {
        let layout = Qwen4ExpNGramHash.headVocabLayout(
            ngramHeads: 3, pleLayerIndex: 0, ngramVocabSizeBase: 100_000)
        #expect(layout.sizes == [100_003, 100_019, 100_043])
        #expect(layout.offsets == [0, 100_003, 200_022])
        #expect(layout.total == 300_065)
    }
}

extension Qwen4ExpNGramHashTests {
    /// End-to-end goldens generated by running the campaign's ngram.py
    /// (NGramHasher vocab=1000, eos=7, ngram=3, heads=2, base=101, seed=1234,
    /// ple=0) — including an EOS mid-sequence and a decode step with carried
    /// context.
    @Test("hash_tokens matches the reference incl. EOS segmentation")
    func hashTokensGoldens() {
        let mult = Qwen4ExpNGramHash.layerMultipliers(
            unigramVocabSize: 1000, ngramSize: 3, pleLayerIndex: 0, seed: 1234)
            .map { Int64(bitPattern: $0) }
        #expect(mult == [5_159_850_018_220_775, 4_902_196_785_138_501, 6_891_410_296_393_783])
        let layout = Qwen4ExpNGramHash.headVocabLayout(
            ngramHeads: 4, pleLayerIndex: 0, ngramVocabSizeBase: 101)
        #expect(layout.sizes == [101, 103, 107, 109])
        #expect(layout.offsets == [0, 101, 204, 311])

        // prefill: prev context = EOS-fill, ids [5,9,7,3,4,11]
        let history: [[Int64]] = [[7, 7, 5, 9, 7, 3, 4, 11]]
        let rows = Qwen4ExpNGramHash.hashHistory(
            history, multipliers: mult,
            headVocabSizes: layout.sizes, headOffsets: layout.offsets,
            ngramSize: 3, headsPerNgram: 2, eosTokenId: 7)
        let tail = Array(rows[0].suffix(6))
        let expected: [[Int64]] = [
            [84, 118, 291, 394], [56, 175, 222, 355], [70, 184, 303, 312],
            [33, 159, 204, 416], [59, 101, 259, 377], [9, 110, 281, 416],
        ]
        #expect(tail == expected)

        // decode step: prev context [4, 11], new token 12
        let decodeRows = Qwen4ExpNGramHash.hashHistory(
            [[4, 11, 12]], multipliers: mult,
            headVocabSizes: layout.sizes, headOffsets: layout.offsets,
            ngramSize: 3, headsPerNgram: 2, eosTokenId: 7)
        #expect(Array(decodeRows[0].suffix(1)) == [[69, 183, 308, 389]])
    }
}
