#!/usr/bin/env python3
"""Inline this checkout's MLX headers for custom Metal prefill kernels.

No installed Python MLX dependency or network access. Run after updating Cmlx;
the recorded source hashes make stale generated headers detectable.
"""
from pathlib import Path
import hashlib
import re

ROOT = Path(__file__).resolve().parents[2]
SOURCE = ROOT / "Source/Cmlx/mlx"
KERNELS = "mlx/backend/metal/kernels/"
hashes = {}


def expand(name, seen):
    if name in seen:
        return ""
    seen.add(name)
    data = (SOURCE / name).read_bytes()
    hashes[name] = hashlib.sha256(data).hexdigest()
    lines = []
    for line in data.decode().splitlines():
        match = re.match(r'\s*#include\s+"(mlx/[^"]+)"', line)
        if match:
            lines.append(expand(match[1], seen))
        elif line.strip() != "#pragma once":
            lines.append(line)
    return "\n".join(lines)


def header(files):
    seen = set()
    expand(KERNELS + "utils.h", seen)  # MLX supplies its transitive preamble.
    return "\n".join(expand(KERNELS + f, seen) for f in files)


nax = header(["steel/gemm/gemm.h", "steel/gemm/nax.h", "steel/gemm/loader.h", "quantized_nax.h"])
steel = header(["steel/gemm/gemm.h", "quantized_utils.h", "quantized.h"])
output = "// Copyright © 2023-2026 Apple Inc.\n// SPDX-License-Identifier: MIT\n"
output += "// Generated by tools/jangh/generate-prefill-headers.py; do not edit.\n"
output += "\n".join("// " + p + " sha256=" + h for p, h in sorted(hashes.items())) + "\n"
output += "enum JANGHPrefillHeaders {\n"
for name, text in [("nax", nax), ("steel", steel)]:
    output += '    static let ' + name + ' = #"""\n' + text + '\n"""#\n'
output += "}\n"
(ROOT / "Libraries/MLXLMCommon/JANGHPrefillHeaders.swift").write_text(output)
